version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - dbvol:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 80:8080

volumes:
  dbvol:
    driver: pxd
    external: false
    driver_opts:
      size: 2
      repl: 2
